Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/DotPosition:
  EnforcedStyle: trailing

Naming/VariableName:
  EnforcedStyle: snake_case

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/AndOr:
  EnforcedStyle: conditionals

Style/MultilineBlockChain:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize: 
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: true